# Generated by Django 5.0.7 on 2024-07-30 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_username_text_alter_username_text2'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaoPian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
