# Generated by Django 5.0.7 on 2024-07-30 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_taopian'),
    ]

    operations = [
        migrations.AddField(
            model_name='taopian',
            name='text2',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
