# Generated by Django 5.0.7 on 2024-07-30 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_taopian_text2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taopian',
            name='text2',
        ),
    ]
