# Generated by Django 5.0.7 on 2024-07-30 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_taopian_text2'),
    ]

    operations = [
        migrations.AddField(
            model_name='taopian',
            name='text2',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
